# Generated by Django 4.2.24 on 2025-09-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dedupe_cyclelog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cyclelog',
            index=models.Index(fields=['user', '-date'], name='idx_user_date_desc'),
        ),
        migrations.AddConstraint(
            model_name='cyclelog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_entry_per_user_per_day'),
        ),
    ]
